"""empty message

Revision ID: 50825a617918
Revises: 5112d47a7f81
Create Date: 2020-12-08 20:22:16.439756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50825a617918'
down_revision = '5112d47a7f81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.String(length=120), nullable=False))
    op.create_unique_constraint(None, 'user', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'username')
    # ### end Alembic commands ###
